#include "FileFilters.h"

#include <QString>

namespace fedup {

const QString FILE_FILTERS(
	"All types (*.*);;"
	"Normal text file (*.txt);;"
	"Flash Action script file (*.as .mx);;"
	"Ada file (*.ada *.ads *.adb);;"
	"Assembly language source file (*.asm);;"
	"Active Server Pages script file (*.asp *.asp);;"
	"AutoIt (*.au3);;"
	"Unix script file (*.sh *.bsh);;"
	"Batch file (*.bat *.cmd *.nt);;"
	"C source file (*.c);;"
	"Categorical Abstract Machine Language (*.ml *.mli *.sml *.thy);;"
	"CMAKEFILE (*.cmake *.cmake);;"
	"COmmon Business Oriented Language (*.cbl *.cbd *.cdb *.cdc *.cob);;"
	"C++ source file (*.h *.hpp *.hxx *.cpp *.cxx *.cc);;"
	"C# source file (*.cs);;"
	"Cascade Style Sheets File (*.css);;"
	"D programming language (*.d);;"
	"Diff file (*.diff *.patch);;"
	"Fortran source file (*.f *.for *.fSU *.f95 *.f2k);;"
	"Haskell (*.hs *.lhs *.as *.las);;"
	"Hyper Text Markup Language file (*.html *.htm *.shtml *.shtm *.xhtml);;"
	"MS ini file (*.ini *.inf *.reg *.url);;"
	"Inno Setup script (*.iss);;"
	"Java source file (*.java);;"
	"JavaScript file (*.is);;"
	"JavaServer Pages script file (*.isp);;"
	"KiXtart file (*.kix);;"
	"List Processing language file (*.lsp *.lisp);;"
	"Lua source File (*.lua);;"
	"Makefile (*.mak Makefile);;"
	"MATrix LABoratory (*.m);;"
	"MSDOS Style/ASCII Art (*.nfo);;"
	"Nullsoft Scriptable Install System script file (*.nsi *.nsh);;"
	"Pascal source file (*.pas *.inc);;"
	"Perl source file (*.pl *.pm *.plx);;"
	"PHP Hypertext Preprocessor file (*.php *.php3 *.phtml);;"
	"Postscript file (*.ps);;"
	"Windows PowerShell (*.ps1);;"
	"Properties file (*.properties);;"
	"Python file (*.py *.pyw);;"
	"R programming language (*.r);;"
	"Windows Resource file (*.rc);;"
	"Ruby file (*.rb *.rbw);;"
	"Scheme file (*.scm *.smd *.ss);;"
	"Smalltalk file (*.st);;"
	"Structured Query Language file (*.sql);;"
	"Tool Command Language file (*.tcl);;"
	"TeX file (*.tex);;"
	"Visual Basic file (*.vb *.vbs);;"
	"Verilog file (*.v);;"
	"VHSIC Hardware Description Language file (*.vhd *.vhdl);;"
	"eXtensible Markup Language file (*.xml *.xsml *.xsl *.xsd *.kml *.wsdl);;"
	"YAML Ain't Markup Language (*.yml)"
);

} // namespace fedup
